spring:
  datasource:
    url: jdbc:mysql://localhost:3308/chargeit_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

server:
  port: 8090
  error:
    include-message: always