version: "3.7"
services:
  db:
    image: "mysql"
    container_name: chargeit_db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=chargeit_db